<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_3.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_4.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.3132556"/>
    <xacro:property name="track" value="0.4563536" />
    <xacro:property name="wheel_vertical_offset" value="-0.077" />

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0.015 0.0231316650320557 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base_link.STL" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.015 0.0231316650320557 0" rpy="0 0 0"/>
          <geometry>
            <mesh
              filename="package://scout_description/meshes/scout_mini_base_link.STL" />
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="132.3898489950015" />
            <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> -->
            <origin xyz="0.015 0.0231316650320557 0" />
            <inertia ixx="0.185196122711036"
            ixy="4.30144213829512E-08"
            ixz="5.81037523686401E-08"
            iyy="0.364893736238929"
            iyz="-0.000386720198091934"
            izz="0.223868521722778" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->

    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_mini_wheel_1 wheel_prefix="rear_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 1.57 0" />
    </xacro:scout_mini_wheel_1>
    <xacro:scout_mini_wheel_2 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 1.57 0" />
    </xacro:scout_mini_wheel_2>
    <xacro:scout_mini_wheel_3 wheel_prefix="front_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 -1.57 0" />
    </xacro:scout_mini_wheel_3>
    <xacro:scout_mini_wheel_4 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 -1.57 0" />
    </xacro:scout_mini_wheel_4>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find scout_description)/urdf/scout_mini.gazebo" />

    <!-- ========================================================= -->
    <!--                ADDITIONAL COORDINATE FRAMES               -->
    <!-- ========================================================= -->

    <!-- 1. base_footprint (ground projection of base_link) 机器人地盘在地面的投影 到1机器人地盘中心 需要向上移动0.11854m-->
    <link name="base_footprint" />
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0.11854" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child  link="base_link" />
    </joint>

    <!-- <link name="base_footprint" />
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 -0.11854" rpy="0 0 0" />
      <parent link="base_link" />
      <child  link="base_footprint" />
    </joint> -->


    <!-- 2. imu_link (IMU reference frame) 偏移 (0,0,0.124)m（车顶中心） -->
    <link name="imu_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><sphere radius="0.02" /></geometry>
        <material name="IMU_Cyan"><color rgba="0 1 1 1"/></material>
      </visual>
    </link>
    <joint name="imu_joint" type="fixed">
      <origin xyz="0 0 0.12393" rpy="0 0 0" />
      <parent link="base_link" />
      <child  link="imu_link" />
    </joint>

    <!-- 3. gps_link (antenna reference) -->
    <link name="gps">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><cylinder length="0.05" radius="0.015" /></geometry>
        <material name="GPS_Yellow"><color rgba="1 1 0 1"/></material>
      </visual>
    </link>
    <joint name="gps_joint" type="fixed">
      <origin xyz="0 0 0.12393" rpy="0 0 0" />
      <parent link="base_link" />
      <child  link="gps" />
    </joint>

    <!-- 4. lidar_link -->  <!-- 灰色圆柱，偏移 (0.559m 前, 0, 0.268m 上)，pitch +15°（0.262 rad，向下倾斜扫描地面）。 --> 
    <link name="livox_frame">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><cylinder length="0.05" radius="0.03" /></geometry>
        <material name="LIDAR_Grey"><color rgba="0.6 0.6 0.6 1"/></material>
      </visual>
    </link>

    <joint name="lidar_joint" type="fixed">
      <origin xyz="0.55851 0.0 0.26763" rpy="0.0 0.261799 0.0" />
      <parent link="base_link" />
      <child  link="livox_frame" />
    </joint>
    
</robot>
